"""Deterministic placement of objects in the scene.

Three placement modes, evaluated per item in this order:

1. **Anchor** -- the Director declared an `anchor` on this item referencing
   another label that's already been placed. Position is computed
   geometry-aware: `parent_pos +/- (parent_size/2 + child_size/2 + offset)`
   along the axis implied by `placement`.
2. **Centered stacking** -- single-subject prompt heuristic. If NO item
   has an anchor and the brief has <= STACK_THRESHOLD items, force
   `x = 0`, `z = 0` so a "make a flower" / "make a tree" prompt produces
   a vertically aligned stack instead of a scattered grid.
3. **Grid** -- fallback. The original M5 logic: zone y-midpoint, x/z by
   item index across a 5-column grid.

Placer encapsulates state (positions placed so far, label -> index, label
references) so iter_asset_items can resolve anchors incrementally as each
item's geometry is generated by the LLM.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from agent.agents.types import AnchorSpec, ObjectSummaryItem

GRID_COLS = 5
GRID_SPACING = 0.3
STACK_THRESHOLD = 6  # single-subject heuristic kicks in below this count

Vec3 = tuple[float, float, float]
Size3 = tuple[float, float, float]


def place_in_zone(
    zone: str,
    zone_map: dict[str, dict[str, list[float]]],
    index: int = 0,
) -> Vec3:
    """Original grid placement -- kept for back-compat with M5 tests and as
    the fallback path inside Placer."""
    if zone not in zone_map:
        raise ValueError(f"unknown zone: {zone!r}")
    y_range = zone_map[zone]["yRange"]
    y = (y_range[0] + y_range[1]) / 2.0
    col = index % GRID_COLS
    row = index // GRID_COLS
    x = (col - GRID_COLS // 2) * GRID_SPACING
    z = row * GRID_SPACING
    return (float(x), float(y), float(z))


def estimate_size(geometry_type: str, args: list[float]) -> Size3:
    """Best-effort bounding box from THREE.js geometry args.

    Used so anchored placement clears the parent's actual extent rather than
    a fixed 0.3 step. Covers the seven v1 primitives. Unknown types fall back
    to a unit cube.
    """
    if not args:
        return (1.0, 1.0, 1.0)

    a = args + [1.0] * 6  # pad to avoid IndexError on short lists
    if geometry_type == "BoxGeometry":
        return (a[0], a[1], a[2])
    if geometry_type == "SphereGeometry":
        return (2 * a[0], 2 * a[0], 2 * a[0])
    if geometry_type == "CylinderGeometry":
        d = 2 * max(a[0], a[1])
        return (d, a[2], d)
    if geometry_type == "ConeGeometry":
        return (2 * a[0], a[1], 2 * a[0])
    if geometry_type == "PlaneGeometry":
        return (a[0], a[1], 0.01)
    if geometry_type == "TorusGeometry":
        # args = [radius, tube, ...]; bounding box ≈ 2(r + t) on x/z, 2t on y.
        r = a[0]
        t = a[1] if len(args) > 1 else 0.4
        return (2 * (r + t), 2 * t, 2 * (r + t))
    if geometry_type == "CircleGeometry":
        return (2 * a[0], 2 * a[0], 0.01)
    return (1.0, 1.0, 1.0)


def resolve_anchor(
    parent_pos: Vec3,
    parent_size: Size3,
    child_size: Size3,
    anchor: AnchorSpec,
) -> Vec3:
    """Compute child position given parent and the requested placement."""
    px, py, pz = parent_pos
    pw, ph, pd = parent_size
    cw, ch, cd = child_size
    o = anchor.offset
    p = anchor.placement

    if p == "above":
        return (px, py + ph / 2 + ch / 2 + o, pz)
    if p == "below":
        return (px, py - ph / 2 - ch / 2 - o, pz)
    if p == "left":
        return (px - pw / 2 - cw / 2 - o, py, pz)
    if p == "right":
        return (px + pw / 2 + cw / 2 + o, py, pz)
    if p == "front":
        return (px, py, pz + pd / 2 + cd / 2 + o)
    if p == "back":
        return (px, py, pz - pd / 2 - cd / 2 - o)
    if p == "on":
        # On top of, near zero clearance -- e.g. stamen on petals.
        return (px, py + ph / 2 + ch / 2 + 0.01, pz)
    return parent_pos


class Placer:
    """Stateful placement helper. One instance per asset run.

    Caller places each item in declaration order:

        placer = Placer(brief.objectSummary, zone_map)
        for index, item in enumerate(brief.objectSummary):
            details = llm.invoke(...)         # geometry + material
            position = placer.place(index, item, details.geometryType, details.geometryArgs)
            ...

    Items referenced as a `relativeTo` parent that have no anchor of their
    own are treated as roots and placed at `(0, zone_midpoint, 0)` so the
    composition centers visually. This is what fixes the "flower with parts
    scattered around" symptom.
    """

    def __init__(
        self,
        items: list[ObjectSummaryItem],
        zone_map: dict[str, dict[str, list[float]]],
    ) -> None:
        self._items = items
        self._zone_map = zone_map
        self._positions: list[Vec3] = []
        self._sizes: list[Size3] = []
        self._label_to_index: dict[str, int] = {}

        # An item is a "composition root" if it has no anchor itself but at
        # least one OTHER item declares it as relativeTo. Root items go to
        # the center of their zone so anchored children stack symmetrically.
        anchored_targets = {it.anchor.relativeTo for it in items if it.anchor}
        self._roots = {
            it.label for it in items if it.anchor is None and it.label in anchored_targets
        }

        # Stacking heuristic only kicks in for small briefs with no anchors
        # at all -- multi-subject prompts ("show how a tomato grows") still
        # use the grid so multiple subjects don't pile on the same x=0.
        self._has_any_anchor = any(it.anchor for it in items)
        self._use_stacking = (
            not self._has_any_anchor and len(items) <= STACK_THRESHOLD
        )

    def place(
        self,
        index: int,
        item: ObjectSummaryItem,
        geometry_type: str,
        geometry_args: list[float],
    ) -> Vec3:
        size = estimate_size(geometry_type, geometry_args)

        if item.anchor and item.anchor.relativeTo in self._label_to_index:
            parent_idx = self._label_to_index[item.anchor.relativeTo]
            position = resolve_anchor(
                self._positions[parent_idx],
                self._sizes[parent_idx],
                size,
                item.anchor,
            )
        elif item.label in self._roots:
            position = self._zone_center(item.zone)
        elif self._use_stacking:
            position = self._zone_center(item.zone)
        else:
            position = place_in_zone(item.zone, self._zone_map, index)

        self._positions.append(position)
        self._sizes.append(size)
        self._label_to_index[item.label] = index
        return position

    def _zone_center(self, zone: str) -> Vec3:
        if zone not in self._zone_map:
            raise ValueError(f"unknown zone: {zone!r}")
        y_range = self._zone_map[zone]["yRange"]
        return (0.0, (y_range[0] + y_range[1]) / 2.0, 0.0)
